# This file was generated by GoReleaser. DO NOT EDIT.
cask "cog-cli" do
  version "0.0.10-beta"

  on_macos do
    on_intel do
      sha256 "8a5b90ab5d54a3c6ebc7407b49d90b40e2a03a942bb73caaae0f00b1252927b5"
      url "https://github.com/srkirve77/cog/releases/download/v#{version}/cog_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c3c141f9311229bd0a543d8806b16960ed7a8921124a8aff9e014251800c8bff"
      url "https://github.com/srkirve77/cog/releases/download/v#{version}/cog_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0cff7431d87972dd5498bd3664f14922328223cf54fb8931f74de5a5660bf432"
      url "https://github.com/srkirve77/cog/releases/download/v#{version}/cog_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "fc3db2b0b3a02bb5ddcc5f4bc22b6a453a7bf5e83d40bbeb25b48ad07ce6a422"
      url "https://github.com/srkirve77/cog/releases/download/v#{version}/cog_Linux_arm64.tar.gz"
    end
  end

  name "cog-cli"
  desc "AI coding agent for the terminal — conversational LLM interface with tool-calling"
  homepage "https://github.com/srkirve77/cog"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cog-cli"

  # No zap stanza required

end
