# This file was generated by GoReleaser. DO NOT EDIT.
cask "cog-cli" do
  version "0.0.11-beta"

  on_macos do
    on_intel do
      sha256 "41f263b98853867fb1287a7ba5db2a2f59cc29ae3aafb09ef2b2d084bfa4b866"
      url "https://github.com/srkirve77/cog/releases/download/v#{version}/cog_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "96457fd52e9b9d37f9a97650f8e4f2b21a5028d53c377959600fdd984a54925d"
      url "https://github.com/srkirve77/cog/releases/download/v#{version}/cog_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3dafbfeacee6de48f88d45c79c64d588cfe6ea57eb8c5aaa52b0d7443d76ec74"
      url "https://github.com/srkirve77/cog/releases/download/v#{version}/cog_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "be3ffd18d347b8704b58e8fbbb40e289e6d3927b157b89d814e247366c3d9ddb"
      url "https://github.com/srkirve77/cog/releases/download/v#{version}/cog_Linux_arm64.tar.gz"
    end
  end

  name "cog-cli"
  desc "AI coding agent for the terminal — conversational LLM interface with tool-calling"
  homepage "https://github.com/srkirve77/cog"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cog-cli"

  # No zap stanza required

end
