# This file was generated by GoReleaser. DO NOT EDIT.
cask "cog-cli" do
  version "0.0.14-beta"

  on_macos do
    on_intel do
      sha256 "5344b72cb8cdf91a0716f57f53d6a3c935c738daf144a8235973afbe563a7099"
      url "https://github.com/srkirve77/cog/releases/download/v#{version}/cog_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a0d2de02a33a6277097010648e85efa1a63290b362c8dcf75c19c03b17c9e428"
      url "https://github.com/srkirve77/cog/releases/download/v#{version}/cog_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "548f6798449240afa01b370c7217ee0a602c7f331f1fe516a23bb14c54343ccd"
      url "https://github.com/srkirve77/cog/releases/download/v#{version}/cog_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7020c03ccea7a9b228525a022454f46d57aff8cbeb7340240c408952dff688ae"
      url "https://github.com/srkirve77/cog/releases/download/v#{version}/cog_Linux_arm64.tar.gz"
    end
  end

  name "cog-cli"
  desc "AI coding agent for the terminal — conversational LLM interface with tool-calling"
  homepage "https://github.com/srkirve77/cog"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cog-cli"

  # No zap stanza required

end
