# This file was generated by GoReleaser. DO NOT EDIT.
cask "cog" do
  version "0.0.9-beta"

  on_macos do
    on_intel do
      sha256 "1b5fc7b8c5fecbaf5bfce3a7f17387259783e26c38b4d91a10677c8e1b687722"
      url "https://github.com/srkirve77/cog/releases/download/v#{version}/cog_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "cca291d4e813be61dad1ac62e0a9a6af5d90f27a2b53b57c668157fd3661a0e0"
      url "https://github.com/srkirve77/cog/releases/download/v#{version}/cog_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "14c2c99866ab2fd670087c35f28239642498c40a6d3a5b06d82efc4bef8f618a"
      url "https://github.com/srkirve77/cog/releases/download/v#{version}/cog_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "fee1121375f36fe16f11db7005c6035b46b43a2f5e41d174282cc1c4f637e649"
      url "https://github.com/srkirve77/cog/releases/download/v#{version}/cog_Linux_arm64.tar.gz"
    end
  end

  name "cog"
  desc "AI coding agent for the terminal — conversational LLM interface with tool-calling"
  homepage "https://github.com/srkirve77/cog"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cog"

  # No zap stanza required

end
