# This file was generated by GoReleaser. DO NOT EDIT.
cask "cog" do
  version "0.0.4-beta"

  on_macos do
    on_intel do
      sha256 "a656213e57ca8c6f9138c76d38d20c95313e8a2bc2359557498661b5c3aeb84a"
      url "https://github.com/srkirve77/cog/releases/download/v#{version}/cog_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "40e4554aee7ce3e3c4584c355f9272dcf998bb897157a02138e921a9324afc92"
      url "https://github.com/srkirve77/cog/releases/download/v#{version}/cog_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2c748a1d049e81b250fe7d87b769c395690948ce5d69e5d271add111554c4ec2"
      url "https://github.com/srkirve77/cog/releases/download/v#{version}/cog_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f382972b3f7b3d8ce7c0e460a868da3f86253fe0e844f140a41fe07ceb036138"
      url "https://github.com/srkirve77/cog/releases/download/v#{version}/cog_Linux_arm64.tar.gz"
    end
  end

  name "cog"
  desc "AI Coding Agent"
  homepage "https://github.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cog"

  # No zap stanza required

end
