# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cog < Formula
  desc "AI command line tool"
  homepage "https://github.com"
  version "0.0.6-beta"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/srkirve77/cog/releases/download/v0.0.6-beta/cog_Darwin_x86_64.tar.gz"
      sha256 "35089b46f9ff90717a2ff9a8ff794750098015e85bcd2f2a02063bf20c829f65"

      define_method(:install) do
        bin.install "cog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/srkirve77/cog/releases/download/v0.0.6-beta/cog_Darwin_arm64.tar.gz"
      sha256 "22d171c0520e439c86614c56b82af4be08d87991abd7e99d097866d26898aadf"

      define_method(:install) do
        bin.install "cog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/srkirve77/cog/releases/download/v0.0.6-beta/cog_Linux_x86_64.tar.gz"
      sha256 "65d0b9c27f193b10f890fe30a39602aefe7f11ef43f797f0df1c62708b11aef2"
      define_method(:install) do
        bin.install "cog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/srkirve77/cog/releases/download/v0.0.6-beta/cog_Linux_arm64.tar.gz"
      sha256 "772fd3c912fda1f7c279bd6ba458d8640b640803d1e0eeda0dc30f38b1951e4b"
      define_method(:install) do
        bin.install "cog"
      end
    end
  end
end
